#!/usr/bin/python
import os, sys
import record, updater#, plotter

if __name__ == '__main__':
	if sys.argv[1] == 'test':
		command = 'bwctl'
		for a in sys.argv[2:]:
			command += ' ' + a 
	#	f = os.popen(command)
		f = open('test.perf')
		print 'opened'
		r = record.Record(f)

		yourDB = raw_input('host user passwd db: ')
		updater.update_MySQL(r.d, yourDB.split())

	elif sys.argv[1] == 'update':
		for a in sys.argv[2:]:
			command += ' ' + a 
		f = os.popen(command)
		update(f)

	else: 
		plotter.plot()
